---
deployment:
  tasks:
    - export DEPLOYPATH=/home/metaserv/public_html/
    - /bin/cp -fR * $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/.git
    - /bin/rm -f $DEPLOYPATH/.cpanel.yml
    - /bin/rm -f $DEPLOYPATH/sync.bat
    - /bin/rm -f $DEPLOYPATH/deploy.php